export const grammer = [
  {
    id: 1,
    tittle: "Easy",
    describe: "tester",
  },
  {
    id: 2,
    tittle: "Medium",
    describe: "tester",
  },
  {
    id: 3,
    tittle: "Hard",
    describe: "tester",
  },
  {
    id: 4,
    tittle: "Nightmare",
    describe: "tester",
  },
];

export const playsoal = [
  {
    id: 1,
    soal: "The students ________ quietly when the teacher entered the classroom.",
    a: "were talking",
    b: "talks",
    c: "talk",
    d: "is talking",
    correct_answer: "a",
    reason: "karena a adalah bentuk lampau yang sesuai dengan konteks kalimat",
  },
  {
    id: 2,
    soal: "I prefer coffee ________ tea in the morning.",
    a: "than",
    b: "over",
    c: "to",
    d: "against",
    correct_answer: "c",
    reason: "karena c adalah preposisi yang digunakan dengan prefer",
  },
  {
    id: 3,
    soal: "The movie was interesting, ________ it was a bit too long.",
    a: "but",
    b: "because",
    c: "so",
    d: "or",
    correct_answer: "a",
    reason: "karena a adalah kata penghubung yang menunjukkan kontras",
  },
  {
    id: 4,
    soal: "Neither of the two options ________ suitable for the task.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason: "karena neither digunakan dengan kata benda tunggal",
  },
  {
    id: 5,
    soal: "Sheila asked me ________ I had seen her keys.",
    a: "that",
    b: "where",
    c: "what",
    d: "if",
    correct_answer: "d",
    reason: "karena if digunakan dalam pertanyaan tidak langsung",
  },
  {
    id: 6,
    soal: "My sister enjoys playing the piano, and ________, she loves to paint.",
    a: "either",
    b: "so",
    c: "too",
    d: "also",
    correct_answer: "c",
    reason: "karena too menunjukkan kesamaan atau penambahan hal yang sejenis",
  },
  {
    id: 7,
    soal: "The cat is sleeping ________ the bed.",
    a: "in",
    b: "on",
    c: "under",
    d: "between",
    correct_answer: "b",
    reason: "karena on digunakan untuk menyatakan posisi di atas sesuatu",
  },
  {
    id: 8,
    soal: "I have lived in this city ________ five years.",
    a: "since",
    b: "for",
    c: "from",
    d: "until",
    correct_answer: "b",
    reason: "karena for digunakan untuk menyatakan durasi waktu",
  },
  {
    id: 9,
    soal: "She couldn't attend the meeting ________ she was feeling unwell.",
    a: "so",
    b: "although",
    c: "because",
    d: "but",
    correct_answer: "c",
    reason: "karena because menyatakan alasan di belakang tindakan",
  },
  {
    id: 10,
    soal: "My grandparents ________ married for 50 years.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "b",
    reason: "karena are digunakan dengan kata benda jamak seperti grandparents",
  },
  {
    id: 11,
    soal: "It's important to stay hydrated, ________ on hot days.",
    a: "especially",
    b: "however",
    c: "therefore",
    d: "moreover",
    correct_answer: "a",
    reason: "karena especially menunjukkan sesuatu yang penting atau menonjol",
  },
  {
    id: 12,
    soal: "The concert was canceled ________ the bad weather.",
    a: "because",
    b: "despite",
    c: "although",
    d: "because of",
    correct_answer: "d",
    reason: "karena because of menyatakan alasan dan diikuti oleh kata benda",
  },
  {
    id: 13,
    soal: "The children built a sandcastle ________ the beach.",
    a: "at",
    b: "in",
    c: "on",
    d: "by",
    correct_answer: "c",
    reason:
      "karena on digunakan untuk menyatakan lokasi di atas sesuatu yang datar",
  },
  {
    id: 14,
    soal: "Sheila and Maria ________ each other since childhood.",
    a: "know",
    b: "knows",
    c: "known",
    d: "have known",
    correct_answer: "d",
    reason:
      "karena have known menyatakan tindakan yang dimulai di masa lalu dan berlanjut sampai sekarang",
  },
  {
    id: 15,
    soal: "I'm sorry, but I don't have ________ information about that.",
    a: "some",
    b: "any",
    c: "a",
    d: "many",
    correct_answer: "b",
    reason:
      "karena any digunakan untuk menyatakan tidak ada jumlah atau jumlah yang tidak spesifik",
  },
  {
    id: 16,
    soal: "He was late for the meeting ________ his car broke down.",
    a: "because",
    b: "since",
    c: "so",
    d: "if",
    correct_answer: "a",
    reason: "karena because menyatakan alasan di belakang tindakan",
  },
  {
    id: 17,
    soal: "I enjoy reading books ________ science fiction.",
    a: "in",
    b: "on",
    c: "at",
    d: "with",
    correct_answer: "b",
    reason: "karena on digunakan untuk menyatakan topik atau subjek",
  },
  {
    id: 18,
    soal: "Sheila is ________ youngest person in the office.",
    a: "a",
    b: "an",
    c: "the",
    d: "some",
    correct_answer: "c",
    reason:
      "karena the digunakan untuk menyatakan sesuatu yang sudah disebut atau dikenal",
  },
  {
    id: 19,
    soal: "The teacher asked the students to work ________ in pairs.",
    a: "himself",
    b: "themselves",
    c: "itself",
    d: "ourselves",
    correct_answer: "b",
    reason: "karena themselves digunakan untuk menyatakan kelompok orang",
  },
  {
    id: 20,
    soal: "The new restaurant in town is known ________ its delicious pasta dishes.",
    a: "about",
    b: "with",
    c: "for",
    d: "to",
    correct_answer: "c",
    reason: "karena for digunakan untuk menyatakan alasan atau karakteristik",
  },
  {
    id: 21,
    soal: "My parents ________ to visit us next month.",
    a: "plans",
    b: "is planning",
    c: "are planning",
    d: "plan",
    correct_answer: "c",
    reason:
      "karena are planning digunakan untuk menyatakan rencana di masa depan",
  },
  {
    id: 22,
    soal: "I haven't seen that movie, but I heard it's ________ good.",
    a: "quite",
    b: "more",
    c: "most",
    d: "very",
    correct_answer: "a",
    reason:
      "karena quite digunakan untuk menyatakan sesuatu yang cukup baik atau cukup besar",
  },
  {
    id: 23,
    soal: "The museum is closed ________ Sundays.",
    a: "in",
    b: "at",
    c: "on",
    d: "by",
    correct_answer: "c",
    reason: "karena on digunakan untuk menyatakan hari dalam seminggu",
  },
  {
    id: 24,
    soal: "My dog is afraid ________ thunderstorms.",
    a: "to",
    b: "of",
    c: "by",
    d: "with",
    correct_answer: "b",
    reason:
      "karena of digunakan untuk menyatakan ketakutan atau keengganan terhadap sesuatu",
  },
  {
    id: 25,
    soal: "We decided to go to the beach ________ it was a sunny day.",
    a: "although",
    b: "because",
    c: "but",
    d: "so",
    correct_answer: "b",
    reason: "karena because menyatakan alasan di belakang keputusan",
  },
  {
    id: 26,
    soal: "The music in the concert hall is much ________ than the music outside.",
    a: "loud",
    b: "louder",
    c: "loudest",
    d: "more loud",
    correct_answer: "b",
    reason: "karena louder adalah bentuk perbandingan tingkat tinggi dari loud",
  },
  {
    id: 27,
    soal: "My brother ________ his homework when the phone rang.",
    a: "is doing",
    b: "does",
    c: "did",
    d: "do",
    correct_answer: "c",
    reason:
      "karena did digunakan untuk menyatakan tindakan yang terjadi di masa lalu",
  },
  {
    id: 28,
    soal: "The concert was ________ by thousands of fans.",
    a: "see",
    b: "seen",
    c: "saw",
    d: "seeing",
    correct_answer: "c",
    reason: "karena saw adalah bentuk lampau dari see",
  },
  {
    id: 29,
    soal: "The sun ________ in the east.",
    a: "rise",
    b: "rises",
    c: "rising",
    d: "rose",
    correct_answer: "b",
    reason: "karena rises adalah bentuk sekarang dari rise",
  },
  {
    id: 30,
    soal: "My grandparents always ________ us interesting stories from their youth.",
    a: "tell",
    b: "tells",
    c: "told",
    d: "telling",
    correct_answer: "c",
    reason: "karena told adalah bentuk lampau dari tell",
  },
];
