export const grammer = [
  {
    id: 1,
    tittle: "Easy",
    describe:
      "Pastikan Anda memahami dengan baik konsep dasar yang terkait dengan topik atau subjek yang sedang Anda pelajari.",
  },
  {
    id: 2,
    tittle: "Medium",
    describe:
      " Tingkatkan pemahaman Anda dengan mengeksplorasi konsep lebih mendalam. Cari sumber tambahan untuk mendapatkan wawasan lebih banyak.",
  },
  {
    id: 3,
    tittle: "Hard",
    describe:
      " Pertajam pengetahuan Anda dan fokus pada konsep-konsep yang lebih kompleks. Gunakan buku, artikel, atau sumber lainnya yang lebih mendalam.",
  },
  {
    id: 4,
    tittle: "Nightmare",
    describe:
      "Persiapkan diri Anda dengan membaca literatur khusus dan penelitian-penelitian terkini dalam bidang yang bersangkutan.",
  },
];

export const playsoal = [
  {
    id: 1,
    soal: "The students ________ quietly when the teacher entered the classroom.",
    a: "were talking",
    b: "talks",
    c: "talk",
    d: "is talking",
    correct_answer: "a",
    reason: "karena a adalah bentuk lampau yang sesuai dengan konteks kalimat",
  },
  {
    id: 2,
    soal: "I prefer coffee ________ tea in the morning.",
    a: "than",
    b: "over",
    c: "to",
    d: "against",
    correct_answer: "c",
    reason: "karena c adalah preposisi yang digunakan dengan prefer",
  },
  {
    id: 3,
    soal: "The movie was interesting, ________ it was a bit too long.",
    a: "but",
    b: "because",
    c: "so",
    d: "or",
    correct_answer: "a",
    reason: "karena a adalah kata penghubung yang menunjukkan kontras",
  },
  {
    id: 4,
    soal: "Neither of the two options ________ suitable for the task.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason: "karena neither digunakan dengan kata benda tunggal",
  },
  {
    id: 5,
    soal: "Sheila asked me ________ I had seen her keys.",
    a: "that",
    b: "where",
    c: "what",
    d: "if",
    correct_answer: "d",
    reason: "karena if digunakan dalam pertanyaan tidak langsung",
  },
  {
    id: 6,
    soal: "My sister enjoys playing the piano, and ________, she loves to paint.",
    a: "either",
    b: "so",
    c: "too",
    d: "also",
    correct_answer: "c",
    reason: "karena too menunjukkan kesamaan atau penambahan hal yang sejenis",
  },
  {
    id: 7,
    soal: "The cat is sleeping ________ the bed.",
    a: "in",
    b: "on",
    c: "under",
    d: "between",
    correct_answer: "b",
    reason: "karena on digunakan untuk menyatakan posisi di atas sesuatu",
  },
  {
    id: 8,
    soal: "I have lived in this city ________ five years.",
    a: "since",
    b: "for",
    c: "from",
    d: "until",
    correct_answer: "b",
    reason: "karena for digunakan untuk menyatakan durasi waktu",
  },
  {
    id: 9,
    soal: "She couldn't attend the meeting ________ she was feeling unwell.",
    a: "so",
    b: "although",
    c: "because",
    d: "but",
    correct_answer: "c",
    reason: "karena because menyatakan alasan di belakang tindakan",
  },
  {
    id: 10,
    soal: "My grandparents ________ married for 50 years.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "b",
    reason: "karena are digunakan dengan kata benda jamak seperti grandparents",
  },
  {
    id: 11,
    soal: "It's important to stay hydrated, ________ on hot days.",
    a: "especially",
    b: "however",
    c: "therefore",
    d: "moreover",
    correct_answer: "a",
    reason: "karena especially menunjukkan sesuatu yang penting atau menonjol",
  },
  {
    id: 12,
    soal: "The concert was canceled ________ the bad weather.",
    a: "because",
    b: "despite",
    c: "although",
    d: "because of",
    correct_answer: "d",
    reason: "karena because of menyatakan alasan dan diikuti oleh kata benda",
  },
  {
    id: 13,
    soal: "The children built a sandcastle ________ the beach.",
    a: "at",
    b: "in",
    c: "on",
    d: "by",
    correct_answer: "c",
    reason:
      "karena on digunakan untuk menyatakan lokasi di atas sesuatu yang datar",
  },
  {
    id: 14,
    soal: "Sheila and Maria ________ each other since childhood.",
    a: "know",
    b: "knows",
    c: "known",
    d: "have known",
    correct_answer: "d",
    reason:
      "karena have known menyatakan tindakan yang dimulai di masa lalu dan berlanjut sampai sekarang",
  },
  {
    id: 15,
    soal: "I'm sorry, but I don't have ________ information about that.",
    a: "some",
    b: "any",
    c: "a",
    d: "many",
    correct_answer: "b",
    reason:
      "karena any digunakan untuk menyatakan tidak ada jumlah atau jumlah yang tidak spesifik",
  },
  {
    id: 16,
    soal: "He was late for the meeting ________ his car broke down.",
    a: "because",
    b: "since",
    c: "so",
    d: "if",
    correct_answer: "a",
    reason: "karena because menyatakan alasan di belakang tindakan",
  },
  {
    id: 17,
    soal: "I enjoy reading books ________ science fiction.",
    a: "in",
    b: "on",
    c: "at",
    d: "with",
    correct_answer: "b",
    reason: "karena on digunakan untuk menyatakan topik atau subjek",
  },
  {
    id: 18,
    soal: "Sheila is ________ youngest person in the office.",
    a: "a",
    b: "an",
    c: "the",
    d: "some",
    correct_answer: "c",
    reason:
      "karena the digunakan untuk menyatakan sesuatu yang sudah disebut atau dikenal",
  },
  {
    id: 19,
    soal: "The teacher asked the students to work ________ in pairs.",
    a: "himself",
    b: "themselves",
    c: "itself",
    d: "ourselves",
    correct_answer: "b",
    reason: "karena themselves digunakan untuk menyatakan kelompok orang",
  },
  {
    id: 20,
    soal: "The new restaurant in town is known ________ its delicious pasta dishes.",
    a: "about",
    b: "with",
    c: "for",
    d: "to",
    correct_answer: "c",
    reason: "karena for digunakan untuk menyatakan alasan atau karakteristik",
  },
  {
    id: 21,
    soal: "My parents ________ to visit us next month.",
    a: "plans",
    b: "is planning",
    c: "are planning",
    d: "plan",
    correct_answer: "c",
    reason:
      "karena are planning digunakan untuk menyatakan rencana di masa depan",
  },
  {
    id: 22,
    soal: "I haven't seen that movie, but I heard it's ________ good.",
    a: "quite",
    b: "more",
    c: "most",
    d: "very",
    correct_answer: "a",
    reason:
      "karena quite digunakan untuk menyatakan sesuatu yang cukup baik atau cukup besar",
  },
  {
    id: 23,
    soal: "The museum is closed ________ Sundays.",
    a: "in",
    b: "at",
    c: "on",
    d: "by",
    correct_answer: "c",
    reason: "karena on digunakan untuk menyatakan hari dalam seminggu",
  },
  {
    id: 24,
    soal: "My dog is afraid ________ thunderstorms.",
    a: "to",
    b: "of",
    c: "by",
    d: "with",
    correct_answer: "b",
    reason:
      "karena of digunakan untuk menyatakan ketakutan atau keengganan terhadap sesuatu",
  },
  {
    id: 25,
    soal: "We decided to go to the beach ________ it was a sunny day.",
    a: "although",
    b: "because",
    c: "but",
    d: "so",
    correct_answer: "b",
    reason: "karena because menyatakan alasan di belakang keputusan",
  },
  {
    id: 26,
    soal: "The music in the concert hall is much ________ than the music outside.",
    a: "loud",
    b: "louder",
    c: "loudest",
    d: "more loud",
    correct_answer: "b",
    reason: "karena louder adalah bentuk perbandingan tingkat tinggi dari loud",
  },
  {
    id: 27,
    soal: "My brother ________ his homework when the phone rang.",
    a: "is doing",
    b: "does",
    c: "did",
    d: "do",
    correct_answer: "c",
    reason:
      "karena did digunakan untuk menyatakan tindakan yang terjadi di masa lalu",
  },
  {
    id: 28,
    soal: "The concert was ________ by thousands of fans.",
    a: "see",
    b: "seen",
    c: "saw",
    d: "seeing",
    correct_answer: "c",
    reason: "karena saw adalah bentuk lampau dari see",
  },
  {
    id: 29,
    soal: "The sun ________ in the east.",
    a: "rise",
    b: "rises",
    c: "rising",
    d: "rose",
    correct_answer: "b",
    reason: "karena rises adalah bentuk sekarang dari rise",
  },
  {
    id: 30,
    soal: "My grandparents always ________ us interesting stories from their youth.",
    a: "tell",
    b: "tells",
    c: "told",
    d: "telling",
    correct_answer: "c",
    reason: "karena told adalah bentuk lampau dari tell",
  },
];

export const easySoal = [
  {
    id: 1,
    soal: "The students ________ quietly when the teacher entered the classroom.",
    a: "were talking",
    b: "talks",
    c: "talk",
    d: "is talking",
    correct_answer: "a",
    reason: "karena a adalah bentuk lampau yang sesuai dengan konteks kalimat",
  },
  {
    id: 2,
    soal: "I prefer coffee ________ tea in the morning.",
    a: "than",
    b: "over",
    c: "to",
    d: "against",
    correct_answer: "c",
    reason: "karena c adalah preposisi yang digunakan dengan prefer",
  },
  {
    id: 3,
    soal: "Yesterday, I ________ to the store to buy some groceries.",
    a: "go",
    b: "goes",
    c: "went",
    d: "gone",
    correct_answer: "c",
    reason: "karena went adalah bentuk lampau dari go",
  },
  {
    id: 4,
    soal: "She ________ a nice book last week.",
    a: "reads",
    b: "read",
    c: "reading",
    d: "has read",
    correct_answer: "b",
    reason: "karena read adalah bentuk lampau dari read",
  },
  {
    id: 5,
    soal: "Sheila asked me ________ I had seen her keys.",
    a: "that",
    b: "where",
    c: "what",
    d: "if",
    correct_answer: "d",
    reason: "karena if digunakan dalam pertanyaan tidak langsung",
  },
  {
    id: 6,
    soal: "My sister enjoys playing the piano, and ________, she loves to paint.",
    a: "either",
    b: "so",
    c: "too",
    d: "also",
    correct_answer: "c",
    reason: "karena too menunjukkan kesamaan atau penambahan hal yang sejenis",
  },
  {
    id: 7,
    soal: "The cat is sleeping ________ the bed.",
    a: "in",
    b: "on",
    c: "under",
    d: "between",
    correct_answer: "b",
    reason: "karena on digunakan untuk menyatakan posisi di atas sesuatu",
  },
  {
    id: 8,
    soal: "I have lived in this city ________ five years.",
    a: "since",
    b: "for",
    c: "from",
    d: "until",
    correct_answer: "b",
    reason: "karena for digunakan untuk menyatakan durasi waktu",
  },
  {
    id: 9,
    soal: "She couldn't attend the meeting ________ she was feeling unwell.",
    a: "so",
    b: "although",
    c: "because",
    d: "but",
    correct_answer: "c",
    reason: "karena because menyatakan alasan di belakang tindakan",
  },
  {
    id: 10,
    soal: "My grandparents ________ married for 50 years.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "b",
    reason: "karena are digunakan dengan kata benda jamak seperti grandparents",
  },
  {
    id: 11,
    soal: "It's important to stay hydrated, ________ on hot days.",
    a: "especially",
    b: "however",
    c: "therefore",
    d: "moreover",
    correct_answer: "a",
    reason: "karena especially menunjukkan sesuatu yang penting atau menonjol",
  },
  {
    id: 12,
    soal: "The concert was canceled ________ the bad weather.",
    a: "because",
    b: "despite",
    c: "although",
    d: "because of",
    correct_answer: "d",
    reason: "karena because of menyatakan alasan dan diikuti oleh kata benda",
  },
  {
    id: 13,
    soal: "The children built a sandcastle ________ the beach.",
    a: "at",
    b: "in",
    c: "on",
    d: "by",
    correct_answer: "c",
    reason:
      "karena on digunakan untuk menyatakan lokasi di atas sesuatu yang datar",
  },
  {
    id: 14,
    soal: "Sheila and Maria ________ each other since childhood.",
    a: "know",
    b: "knows",
    c: "known",
    d: "have known",
    correct_answer: "d",
    reason:
      "karena have known menyatakan tindakan yang dimulai di masa lalu dan berlanjut sampai sekarang",
  },
  {
    id: 15,
    soal: "I'm sorry, but I don't have ________ information about that.",
    a: "some",
    b: "any",
    c: "a",
    d: "many",
    correct_answer: "b",
    reason:
      "karena any digunakan untuk menyatakan tidak ada jumlah atau jumlah yang tidak spesifik",
  },
  {
    id: 16,
    soal: "He was late for the meeting ________ his car broke down.",
    a: "because",
    b: "since",
    c: "so",
    d: "if",
    correct_answer: "a",
    reason: "karena because menyatakan alasan di belakang tindakan",
  },
  {
    id: 17,
    soal: "I enjoy reading books ________ science fiction.",
    a: "in",
    b: "on",
    c: "at",
    d: "with",
    correct_answer: "b",
    reason: "karena on digunakan untuk menyatakan topik atau subjek",
  },
  {
    id: 18,
    soal: "Sheila is ________ youngest person in the office.",
    a: "a",
    b: "an",
    c: "the",
    d: "some",
    correct_answer: "c",
    reason:
      "karena the digunakan untuk menyatakan sesuatu yang sudah disebut atau dikenal",
  },
  {
    id: 19,
    soal: "The teacher asked the students to work ________ in pairs.",
    a: "himself",
    b: "themselves",
    c: "itself",
    d: "ourselves",
    correct_answer: "b",
    reason: "karena themselves digunakan untuk menyatakan kelompok orang",
  },
  {
    id: 20,
    soal: "The new restaurant in town is known ________ its delicious pasta dishes.",
    a: "about",
    b: "with",
    c: "for",
    d: "to",
    correct_answer: "c",
    reason: "karena for digunakan untuk menyatakan alasan atau karakteristik",
  },
  {
    id: 21,
    soal: "My parents ________ to visit us next month.",
    a: "plans",
    b: "is planning",
    c: "are planning",
    d: "plan",
    correct_answer: "c",
    reason:
      "karena are planning digunakan untuk menyatakan rencana di masa depan",
  },
  {
    id: 22,
    soal: "I haven't seen that movie, but I heard it's ________ good.",
    a: "quite",
    b: "more",
    c: "most",
    d: "very",
    correct_answer: "a",
    reason:
      "karena quite digunakan untuk menyatakan sesuatu yang cukup baik atau cukup besar",
  },
  {
    id: 23,
    soal: "The museum is closed ________ Sundays.",
    a: "in",
    b: "at",
    c: "on",
    d: "by",
    correct_answer: "c",
    reason: "karena on digunakan untuk menyatakan hari dalam seminggu",
  },
  {
    id: 24,
    soal: "My dog is afraid ________ thunderstorms.",
    a: "to",
    b: "of",
    c: "by",
    d: "with",
    correct_answer: "b",
    reason:
      "karena of digunakan untuk menyatakan ketakutan atau keengganan terhadap sesuatu",
  },
  {
    id: 25,
    soal: "We decided to go to the beach ________ it was a sunny day.",
    a: "although",
    b: "because",
    c: "but",
    d: "so",
    correct_answer: "b",
    reason: "karena because menyatakan alasan di belakang keputusan",
  },
  {
    id: 26,
    soal: "The music in the concert hall is much ________ than the music outside.",
    a: "loud",
    b: "louder",
    c: "loudest",
    d: "more loud",
    correct_answer: "b",
    reason: "karena louder adalah bentuk perbandingan tingkat tinggi dari loud",
  },
  {
    id: 27,
    soal: "My brother ________ his homework when the phone rang.",
    a: "is doing",
    b: "does",
    c: "did",
    d: "do",
    correct_answer: "c",
    reason:
      "karena did digunakan untuk menyatakan tindakan yang terjadi di masa lalu",
  },
  {
    id: 28,
    soal: "The concert was ________ by thousands of fans.",
    a: "see",
    b: "seen",
    c: "saw",
    d: "seeing",
    correct_answer: "c",
    reason: "karena saw adalah bentuk lampau dari see",
  },
  {
    id: 29,
    soal: "The sun ________ in the east.",
    a: "rise",
    b: "rises",
    c: "rising",
    d: "rose",
    correct_answer: "b",
    reason: "karena rises adalah bentuk sekarang dari rise",
  },
  {
    id: 30,
    soal: "My grandparents always ________ us interesting stories from their youth.",
    a: "tell",
    b: "tells",
    c: "told",
    d: "telling",
    correct_answer: "c",
    reason: "karena told adalah bentuk lampau dari tell",
  },
];

export const mediumSoal = [
  {
    id: 1,
    soal: "John ________ his keys. He can't find them anywhere.",
    a: "loses",
    b: "losing",
    c: "has lost",
    d: "will lose",
    correct_answer: "c",
    reason:
      "karena has lost adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 2,
    soal: "We ________ dinner by the time they arrive.",
    a: "have",
    b: "has",
    c: "had",
    d: "having",
    correct_answer: "a",
    reason:
      "karena have adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 3,
    soal: "She ________ that movie before, so she doesn't want to watch it again.",
    a: "sees",
    b: "seeing",
    c: "saw",
    d: "has seen",
    correct_answer: "d",
    reason:
      "karena has seen adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 4,
    soal: "I ________ my keys at home this morning, but now I can't find them.",
    a: "leave",
    b: "leaving",
    c: "left",
    d: "has left",
    correct_answer: "c",
    reason:
      "karena left adalah bentuk past tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 5,
    soal: "By the time I arrived, they ________ already left.",
    a: "has",
    b: "have",
    c: "had",
    d: "having",
    correct_answer: "c",
    reason:
      "karena had adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 6,
    soal: "She ________ a new job, and she's very excited about it.",
    a: "get",
    b: "getting",
    c: "got",
    d: "has got",
    correct_answer: "d",
    reason:
      "karena has got adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 7,
    soal: "They ________ each other for over ten years.",
    a: "know",
    b: "knows",
    c: "known",
    d: "have known",
    correct_answer: "d",
    reason:
      "karena have known adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 8,
    soal: "I ________ this book for months, but I still haven't finished it.",
    a: "read",
    b: "reads",
    c: "reading",
    d: "have been reading",
    correct_answer: "d",
    reason:
      "karena have been reading adalah bentuk present perfect continuous tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 9,
    soal: "She ________ at the company since 2010.",
    a: "work",
    b: "works",
    c: "working",
    d: "has been working",
    correct_answer: "d",
    reason:
      "karena has been working adalah bentuk present perfect continuous tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 10,
    soal: "The kids ________ their homework already.",
    a: "finish",
    b: "finishes",
    c: "finished",
    d: "finishing",
    correct_answer: "c",
    reason:
      "karena finished adalah bentuk past tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 11,
    soal: "I ________ this restaurant before, and the food was delicious.",
    a: "visit",
    b: "visits",
    c: "visited",
    d: "visiting",
    correct_answer: "c",
    reason:
      "karena visited adalah bentuk past tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 12,
    soal: "They ________ to Paris several times.",
    a: "go",
    b: "goes",
    c: "went",
    d: "going",
    correct_answer: "c",
    reason:
      "karena went adalah bentuk past tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 13,
    soal: "She ________ to that concert last night.",
    a: "go",
    b: "goes",
    c: "went",
    d: "going",
    correct_answer: "c",
    reason:
      "karena went adalah bentuk past tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 14,
    soal: "We ________ each other since we were kids.",
    a: "know",
    b: "knows",
    c: "known",
    d: "have known",
    correct_answer: "d",
    reason:
      "karena have known adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 15,
    soal: "I ________ this book for a week and I still haven't finished it.",
    a: "read",
    b: "reads",
    c: "reading",
    d: "have been reading",
    correct_answer: "d",
    reason:
      "karena have been reading adalah bentuk present perfect continuous tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 16,
    soal: "They ________ each other for over twenty years.",
    a: "know",
    b: "knows",
    c: "known",
    d: "have known",
    correct_answer: "d",
    reason:
      "karena have known adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 17,
    soal: "I ________ this movie already, so I don't want to watch it again.",
    a: "see",
    b: "seeing",
    c: "saw",
    d: "have seen",
    correct_answer: "d",
    reason:
      "karena have seen adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 18,
    soal: "She ________ her keys at home this morning, but now she can't find them.",
    a: "leave",
    b: "leaving",
    c: "left",
    d: "has left",
    correct_answer: "d",
    reason:
      "karena has left adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 19,
    soal: "He ________ the news on the radio when it happened.",
    a: "hear",
    b: "hears",
    c: "heard",
    d: "hearing",
    correct_answer: "c",
    reason:
      "karena heard adalah bentuk past tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 20,
    soal: "We ________ our friend for years before she moved to another country.",
    a: "know",
    b: "knows",
    c: "known",
    d: "have known",
    correct_answer: "d",
    reason:
      "karena have known adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 21,
    soal: "They ________ to the new house last month.",
    a: "move",
    b: "moves",
    c: "moved",
    d: "moving",
    correct_answer: "c",
    reason:
      "karena moved adalah bentuk past tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 22,
    soal: "She ________ that book many times.",
    a: "read",
    b: "reads",
    c: "reading",
    d: "has read",
    correct_answer: "d",
    reason:
      "karena has read adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 23,
    soal: "We ________ in this city since we got married.",
    a: "live",
    b: "lives",
    c: "lived",
    d: "living",
    correct_answer: "c",
    reason:
      "karena lived adalah bentuk past tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 24,
    soal: "He ________ his computer for over five years.",
    a: "use",
    b: "uses",
    c: "used",
    d: "using",
    correct_answer: "c",
    reason:
      "karena used adalah bentuk past tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 25,
    soal: "She ________ her keys at home this morning, but now she can't find them.",
    a: "leave",
    b: "leaving",
    c: "left",
    d: "has left",
    correct_answer: "d",
    reason:
      "karena has left adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 26,
    soal: "I ________ this book for a week and I still haven't finished it.",
    a: "read",
    b: "reads",
    c: "reading",
    d: "have been reading",
    correct_answer: "d",
    reason:
      "karena have been reading adalah bentuk present perfect continuous tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 27,
    soal: "They ________ each other for over twenty years.",
    a: "know",
    b: "knows",
    c: "known",
    d: "have known",
    correct_answer: "d",
    reason:
      "karena have known adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 28,
    soal: "I ________ this movie already, so I don't want to watch it again.",
    a: "see",
    b: "seeing",
    c: "saw",
    d: "have seen",
    correct_answer: "d",
    reason:
      "karena have seen adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 29,
    soal: "He ________ the news on the radio when it happened.",
    a: "hear",
    b: "hears",
    c: "heard",
    d: "hearing",
    correct_answer: "c",
    reason:
      "karena heard adalah bentuk past tense yang sesuai dengan konteks kalimat",
  },
  {
    id: 30,
    soal: "We ________ our friend for years before she moved to another country.",
    a: "know",
    b: "knows",
    c: "known",
    d: "have known",
    correct_answer: "d",
    reason:
      "karena have known adalah bentuk present perfect tense yang sesuai dengan konteks kalimat",
  },
];

export const hardSoal = [
  {
    id: 1,
    soal: "If he ________ earlier, he would have caught the train.",
    a: "leave",
    b: "leaves",
    c: "left",
    d: "leaving",
    correct_answer: "c",
    reason:
      "karena left adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 2,
    soal: "You ________ more money if you had invested wisely.",
    a: "have",
    b: "has",
    c: "had",
    d: "having",
    correct_answer: "c",
    reason:
      "karena had adalah bentuk past perfect tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 3,
    soal: "If it ________ raining, we would have gone for a walk.",
    a: "stop",
    b: "stops",
    c: "stopped",
    d: "stopping",
    correct_answer: "c",
    reason:
      "karena stopped adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 4,
    soal: "She ________ English better if she had taken the course.",
    a: "speaks",
    b: "speak",
    c: "spoke",
    d: "speaking",
    correct_answer: "a",
    reason:
      "karena speaks adalah bentuk present simple tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 5,
    soal: "I ________ you if I had known you were in town.",
    a: "visit",
    b: "visits",
    c: "visited",
    d: "visiting",
    correct_answer: "c",
    reason:
      "karena visited adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 6,
    soal: "If she ________ harder, she would have passed the exam.",
    a: "study",
    b: "studies",
    c: "studied",
    d: "studying",
    correct_answer: "c",
    reason:
      "karena studied adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 7,
    soal: "You will succeed if you ________ your best effort into it.",
    a: "put",
    b: "puts",
    c: "putting",
    d: "putted",
    correct_answer: "a",
    reason:
      "karena put adalah bentuk present simple tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 8,
    soal: "Unless you ________ the invitation, you won't be able to attend the party.",
    a: "accept",
    b: "accepts",
    c: "accepted",
    d: "accepting",
    correct_answer: "c",
    reason:
      "karena accepted adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 9,
    soal: "If she ________ to the meeting, she would have heard the news.",
    a: "come",
    b: "comes",
    c: "came",
    d: "coming",
    correct_answer: "c",
    reason:
      "karena came adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 10,
    soal: "I ________ if I were you.",
    a: "go",
    b: "goes",
    c: "went",
    d: "gone",
    correct_answer: "a",
    reason:
      "karena go adalah bentuk present simple tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 11,
    soal: "She ________ the job if she had applied earlier.",
    a: "get",
    b: "gets",
    c: "got",
    d: "getting",
    correct_answer: "c",
    reason:
      "karena got adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 12,
    soal: "If I ________ her phone number, I would have called her.",
    a: "have",
    b: "has",
    c: "had",
    d: "having",
    correct_answer: "c",
    reason:
      "karena had adalah bentuk past perfect tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 13,
    soal: "He ________ a promotion if he had performed better.",
    a: "get",
    b: "gets",
    c: "got",
    d: "getting",
    correct_answer: "c",
    reason:
      "karena got adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 14,
    soal: "You ________ the match if you had trained harder.",
    a: "win",
    b: "wins",
    c: "won",
    d: "winning",
    correct_answer: "c",
    reason:
      "karena won adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 15,
    soal: "If you ________ him earlier, you could have helped him.",
    a: "meet",
    b: "meets",
    c: "met",
    d: "meeting",
    correct_answer: "c",
    reason:
      "karena met adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 16,
    soal: "They ________ the competition if they had practiced more.",
    a: "win",
    b: "wins",
    c: "won",
    d: "winning",
    correct_answer: "c",
    reason:
      "karena won adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 17,
    soal: "If you ________ earlier, you could have caught the bus.",
    a: "leave",
    b: "leaves",
    c: "left",
    d: "leaving",
    correct_answer: "c",
    reason:
      "karena left adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 18,
    soal: "She ________ the award if she had submitted her project on time.",
    a: "win",
    b: "wins",
    c: "won",
    d: "winning",
    correct_answer: "c",
    reason:
      "karena won adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 19,
    soal: "If he ________ more effort, he would have achieved better results.",
    a: "put",
    b: "puts",
    c: "putting",
    d: "putted",
    correct_answer: "a",
    reason:
      "karena put adalah bentuk present simple tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 20,
    soal: "You ________ the opportunity if you had applied for the scholarship.",
    a: "miss",
    b: "misses",
    c: "missed",
    d: "missing",
    correct_answer: "c",
    reason:
      "karena missed adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 21,
    soal: "If she ________ her passport, she could have traveled with us.",
    a: "bring",
    b: "brings",
    c: "brought",
    d: "bringing",
    correct_answer: "c",
    reason:
      "karena brought adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 22,
    soal: "He ________ if he had taken the necessary precautions.",
    a: "fall",
    b: "falls",
    c: "fell",
    d: "falling",
    correct_answer: "c",
    reason:
      "karena fell adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 23,
    soal: "If you ________ the instructions, you would have assembled it correctly.",
    a: "follow",
    b: "follows",
    c: "following",
    d: "followed",
    correct_answer: "d",
    reason:
      "karena followed adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 24,
    soal: "They ________ the challenge if they had trained harder.",
    a: "complete",
    b: "completes",
    c: "completed",
    d: "completing",
    correct_answer: "c",
    reason:
      "karena completed adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 25,
    soal: "If she ________ to the advice, she wouldn't be in this situation.",
    a: "listen",
    b: "listens",
    c: "listened",
    d: "listening",
    correct_answer: "c",
    reason:
      "karena listened adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 26,
    soal: "You ________ the exam if you had studied more.",
    a: "pass",
    b: "passes",
    c: "passed",
    d: "passing",
    correct_answer: "c",
    reason:
      "karena passed adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 27,
    soal: "If he ________ earlier, he would have avoided the traffic.",
    a: "leave",
    b: "leaves",
    c: "left",
    d: "leaving",
    correct_answer: "c",
    reason:
      "karena left adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 28,
    soal: "She ________ the opportunity if she had applied on time.",
    a: "miss",
    b: "misses",
    c: "missed",
    d: "missing",
    correct_answer: "c",
    reason:
      "karena missed adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 29,
    soal: "If you ________ earlier, you would have seen the sunrise.",
    a: "wake",
    b: "wakes",
    c: "waking",
    d: "woke",
    correct_answer: "d",
    reason:
      "karena woke adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
  {
    id: 30,
    soal: "You ________ if you had followed the doctor's advice.",
    a: "recover",
    b: "recovers",
    c: "recovered",
    d: "recovering",
    correct_answer: "c",
    reason:
      "karena recovered adalah bentuk past tense yang sesuai dengan konteks kalimat conditional",
  },
];

export const nightmareSoal = [
  {
    id: 1,
    soal: "The phenomenon, along with its implications, ________ still being studied by scientists.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason:
      "karena is adalah bentuk singular verb yang sesuai dengan subject 'phenomenon'.",
  },
  {
    id: 2,
    soal: "Neither the director nor the actors ________ satisfied with the final cut of the film.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "b",
    reason:
      "karena are adalah bentuk plural verb yang sesuai dengan subject 'director' dan 'actors'.",
  },
  {
    id: 3,
    soal: "The committee, who ________ been working tirelessly, is about to present their findings.",
    a: "has",
    b: "have",
    c: "is",
    d: "am",
    correct_answer: "a",
    reason:
      "karena has adalah bentuk singular verb yang sesuai dengan subject 'committee'.",
  },
  {
    id: 4,
    soal: "One of the most difficult languages to learn ________ Mandarin.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason:
      "karena is adalah bentuk singular verb yang sesuai dengan subject 'one'.",
  },
  {
    id: 5,
    soal: "The data, as well as the conclusions, ________ been carefully examined.",
    a: "has",
    b: "have",
    c: "is",
    d: "am",
    correct_answer: "a",
    reason:
      "karena has adalah bentuk singular verb yang sesuai dengan subject 'data'.",
  },
  {
    id: 6,
    soal: "Each of the students ________ a unique perspective on the topic.",
    a: "has",
    b: "have",
    c: "is",
    d: "am",
    correct_answer: "a",
    reason:
      "karena has adalah bentuk singular verb yang sesuai dengan subject 'each'.",
  },
  {
    id: 7,
    soal: "The number of applicants for the job ________ higher than expected.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason:
      "karena is adalah bentuk singular verb yang sesuai dengan subject 'number'.",
  },
  {
    id: 8,
    soal: "Either the manager or the team members ________ responsible for the mistake.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "b",
    reason:
      "karena are adalah bentuk plural verb yang sesuai dengan subject 'manager' dan 'team members'.",
  },
  {
    id: 9,
    soal: "Not only the students but also the teacher ________ surprised by the test results.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "b",
    reason:
      "karena are adalah bentuk plural verb yang sesuai dengan subject 'students' dan 'teacher'.",
  },
  {
    id: 10,
    soal: "A variety of options ________ available for the customers to choose from.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "b",
    reason:
      "karena are adalah bentuk plural verb yang sesuai dengan subject 'variety'.",
  },
  {
    id: 11,
    soal: "The majority of the evidence ________ in favor of the defendant.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason:
      "karena is adalah bentuk singular verb yang sesuai dengan subject 'majority'.",
  },
  {
    id: 12,
    soal: "The number of participants in the workshop ________ steadily increasing.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason:
      "karena is adalah bentuk singular verb yang sesuai dengan subject 'number'.",
  },
  {
    id: 13,
    soal: "Neither the president nor the vice president ________ aware of the situation.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason:
      "karena is adalah bentuk singular verb yang sesuai dengan subject 'president' dan 'vice president'.",
  },
  {
    id: 14,
    soal: "Several cases of the disease ________ reported in the region.",
    a: "has",
    b: "have",
    c: "is",
    d: "am",
    correct_answer: "b",
    reason:
      "karena have adalah bentuk plural verb yang sesuai dengan subject 'cases'.",
  },
  {
    id: 15,
    soal: "Each of the books on the shelf ________ its own story.",
    a: "has",
    b: "have",
    c: "is",
    d: "am",
    correct_answer: "a",
    reason:
      "karena has adalah bentuk singular verb yang sesuai dengan subject 'each'.",
  },
  {
    id: 16,
    soal: "The group of musicians ________ performing at the concert next week.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason:
      "karena is adalah bentuk singular verb yang sesuai dengan subject 'group'.",
  },
  {
    id: 17,
    soal: "Not all of the information on the website ________ accurate.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason:
      "karena is adalah bentuk singular verb yang sesuai dengan subject 'information'.",
  },
  {
    id: 18,
    soal: "The majority of the population ________ in urban areas.",
    a: "live",
    b: "lives",
    c: "lived",
    d: "living",
    correct_answer: "b",
    reason:
      "karena lives adalah bentuk singular verb yang sesuai dengan subject 'majority'.",
  },
  {
    id: 19,
    soal: "One of the students ________ already completed the assignment.",
    a: "has",
    b: "have",
    c: "is",
    d: "am",
    correct_answer: "a",
    reason:
      "karena has adalah bentuk singular verb yang sesuai dengan subject 'one'.",
  },
  {
    id: 20,
    soal: "The list of ingredients for the recipe ________ on the kitchen counter.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason:
      "karena is adalah bentuk singular verb yang sesuai dengan subject 'list'.",
  },
  {
    id: 21,
    soal: "Not only the athletes but also the coach ________ ready for the championship.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "b",
    reason:
      "karena are adalah bentuk plural verb yang sesuai dengan subject 'athletes' dan 'coach'.",
  },
  {
    id: 22,
    soal: "The quality of the products ________ important for customer satisfaction.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason:
      "karena is adalah bentuk singular verb yang sesuai dengan subject 'quality'.",
  },
  {
    id: 23,
    soal: "Several members of the committee ________ to attend the conference.",
    a: "refuse",
    b: "refuses",
    c: "refused",
    d: "refusing",
    correct_answer: "a",
    reason:
      "karena refuse adalah bentuk present simple tense yang sesuai dengan konteks kalimat.",
  },
  {
    id: 24,
    soal: "The book, as well as the accompanying CD, ________ available for purchase.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason:
      "karena is adalah bentuk singular verb yang sesuai dengan subject 'book'.",
  },
  {
    id: 25,
    soal: "The committee ________ several recommendations for improvement.",
    a: "makes",
    b: "make",
    c: "making",
    d: "made",
    correct_answer: "b",
    reason:
      "karena make adalah bentuk present simple tense yang sesuai dengan konteks kalimat.",
  },
  {
    id: 26,
    soal: "The concept of time, as well as space, ________ explored in this philosophical work.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason:
      "karena is adalah bentuk singular verb yang sesuai dengan subject 'concept'.",
  },
  {
    id: 27,
    soal: "The majority of the population ________ in favor of the new policy.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason:
      "karena is adalah bentuk singular verb yang sesuai dengan subject 'majority'.",
  },
  {
    id: 28,
    soal: "Neither the manager nor the employees ________ aware of the upcoming changes.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "b",
    reason:
      "karena are adalah bentuk plural verb yang sesuai dengan subject 'manager' dan 'employees'.",
  },
  {
    id: 29,
    soal: "The list of items to be discussed ________ on the agenda for the meeting.",
    a: "is",
    b: "are",
    c: "am",
    d: "be",
    correct_answer: "a",
    reason:
      "karena is adalah bentuk singular verb yang sesuai dengan subject 'list'.",
  },
  {
    id: 30,
    soal: "The team, along with their coach, ________ been training hard for the upcoming match.",
    a: "has",
    b: "have",
    c: "is",
    d: "be",
    correct_answer: "a",
    reason:
      "karena has adalah bentuk singular verb yang sesuai dengan subject 'team'.",
  },
];
